name: Integration tests

on:
  workflow_call:
    inputs:
      shell-installer-url:
        type: string
        required: false

jobs:
  integration-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: ['11', '17']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - run: mvn integration-test -DskipTests --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        shell: bash
        env:
          INPUT_SHELL_INSTALLER_URL: ${{ inputs.shell-installer-url }}
