name: "test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        java: ["11", "17"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir "foo bar"
          cd "foo bar"
          pwd
          cat ../install-cicd.bash | bash -xe
